version: '3.9'
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/project:/project
    networks:
      - ftr

  #######################################

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    networks:
      - ftr

  #######################################

networks:  
  ftr:
    driver: bridge


