# Generated by Django 3.2.7 on 2024-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefactor', '0024_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4a6b0a', max_length=6),
        ),
    ]
